### ISSUE TITLE
fail to install using pip on windows

### ISSUE THREAD

**Issue by shelper** [heroku-python/django-postgrespool#28]
got this error below, i believe it is because i am using windows and use chinese as my system locale. it would be better to save the readme.rst in utf8, which will solve the problem

Collecting django-postgrespool
  Using cached django-postgrespool-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\zyuan\AppData\Local\Temp\pip-build-hixoxdz4\django-postgrespool\setup.py", line 26, in <module>
        long_description=open('README.rst').read(),
    UnicodeDecodeError: 'gbk' codec can't decode byte 0x93 in position 1202: illegal multibyte sequence

**Comment by icyc9** [comment]
Any solution?
