### ISSUE TITLE
Celery jobs throw exceptions

### ISSUE THREAD

**Issue by brockhaywood** [heroku-python/django-postgrespool#3]
When running Celery jobs, there are frequent (but not entirely consistent) exceptions being thrown from the celery jobs.

The most common exception is thrown from libpq with no message:. Here is an example stack trace:

Task main.tasks.scheduled_messages[3768b5f2-ac3e-4e6c-83ad-5b842861d6e7] raised exception: DatabaseError('error with no message from the libpq',)
Traceback (most recent call last):
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/celery/task/trace.py", line 224, in trace_task
    R = retval = fun(_args, *_kwargs)
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/celery/task/trace.py", line 403, in **protected_call**
    return self.run(_args, *_kwargs)
  File "/Users/sendhub-dev/dev/sendhub/project/app/main/tasks.py", line 62, in scheduled_messages
    interactive=False
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/core/management/**init**.py", line 150, in call_command
    return klass.execute(_args, *_defaults)
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/core/management/base.py", line 232, in execute
    output = self.handle(_args, *_options)
  File "/Users/sendhub-dev/dev/sendhub/project/app/main/management/commands/send_scheduled_messages.py", line 21, in handle
    for message in UserMessage.objects.pending().filter(scheduled_at__lte=datetime.utcnow(), sent__isnull=True):
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/models/query.py", line 118, in _result_iter
    self._fill_cache()
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/models/query.py", line 875, in _fill_cache
    self._result_cache.append(self._iter.next())
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/models/query.py", line 291, in iterator
    for row in compiler.results_iter():
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 763, in results_iter
    for rows in self.execute_sql(MULTI):
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 817, in execute_sql
    cursor = self.connection.cursor()
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django/db/backends/__init__.py", line 306, in cursor
    cursor = self.make_debug_cursor(self._cursor())
  File "/Users/sendhub-dev/dev/sendhub/project/venv/lib/python2.7/site-packages/django_postgrespool/base.py", line 78, in _cursor
    self.connection.set_isolation_level(self.isolation_level)
DatabaseError: error with no message from the libpq

**Comment by kennethreitz** [comment]
@ask any ideas?

**Comment by mvantellingen** [comment]
I actually had the same issue when running an SQLAlchemy app under uwsgi. The problem in that case was that uwsgi forked the workers which resulted in sqlalchemy using the same sockets between the workers. In uwsgi this was solved with the -lazy flag. See http://lists.unbit.it/pipermail/uwsgi/2011-May/002079.html

I'm pretty sure this is the same kind of problem.

**Comment by ask** [comment]
What @mvantellingen says sounds about right!  You should use multiprocessing.util.register_after_fork or something.

(though celery uses the billiard fork of multiprocessing which now has its own after fork registry (billiard.util.register_after_fork, I totally forgot about that, and it should really use the multiprocessing one for library consistency)

**Comment by brockhaywood** [comment]
Interesting, we're using gunicorn. I don't see any flags that may help with that but it's a start.

**Comment by saippuakauppias** [comment]
@brockhaywood you solved this problem? I'm get this errors in my sentry just now :-(
I'm also use gunicorn.

**Comment by brockhaywood** [comment]
No, I was unable to resolve.

On Wed, Feb 13, 2013 at 12:08 PM, Denis Veselov notifications@github.comwrote:

> @brockhaywood https://github.com/brockhaywood you solved this problem?
> I'm get this errors in my sentry just now :-(
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kennethreitz/django-postgrespool/issues/3#issuecomment-13515303.

## 
- bh

**Comment by skeet70** [comment]
I'm about to push this to production, our celery tasks are intermittent and non-critical, so I'll add any information we get out of this here.
