### ISSUE TITLE
UnicodeDecodeError while installing on Ubuntu Linux

### ISSUE THREAD

**Issue by lym** [heroku-python/django-postgrespool#30]
I have django-postgrespool as a dependency in my Django application. When I try to install it via pip, I get hit with this error:

```
Downloading from URL https://pypi.python.org/packages/8e/cd/0e9b7c297a84caf6334d1d
bd9da35af50d533f1230b96bc21223d5addc1e/django-postgrespool-0.3.0.tar.gz#md5=39042504
28523e76f057113d07405498 (from https://pypi.python.org/simple/django-postgrespool/)
Running setup.py (path:/tmp/pip_build_gitlab-runner/django-postgrespool/setup.py) 
egg_info for package django-postgrespool
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "/tmp/pip_build_gitlab-runner/django-postgrespool/setup.py", line 26, in <module>
    long_description=open('README.rst').read(),
  File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1200: ordinal not in     range(128)
Complete output from command python setup.py egg_info:
Traceback (most recent call last):

File "<string>", line 17, in <module>

File "/tmp/pip_build_gitlab-runner/django-postgrespool/setup.py", line 26, in <module>

long_description=open('README.rst').read(),

File "/usr/lib/python3.4/encodings/ascii.py", line 26, in decode

return codecs.ascii_decode(input, self.errors)[0]

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 1200: ordinal not in range(128)
```

I am installing on an Ubuntu 14.04.4 LTS (GNU/Linux 3.13.0-76-generic x86_64) machine with python3

**Comment by icyc9** [comment]
Receiving this error too. @lym Have you discovered the cause?

**Comment by dravnjak** [comment]
I have resolved by setting `export LC_ALL=en_US.UTF-8` and than install django-postgrespool.
For me issue was on `export LC_ALL=C` and forcing default language.

**Comment by jandebleser** [comment]
This fixed it for me: https://stackoverflow.com/a/50639442/1876203
```
sed -i -e 's/# en_US.UTF-8 UTF-8/en_US.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
export LANG=en_US.UTF-8  
export LANGUAGE=en_US:en  
export LC_ALL=en_US.UTF-8```

**Comment by jaraco** [comment]
The bug exists in the setup.py / README.rst.
